version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: 'backend/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - ElianVanCutsem
  assignees:
    - ElianVanCutsem
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
